// Generated from ESPN's public team API (site.api.espn.com) — official
// current team logos. Regenerate: fetch /v2/sports/{league}/teams per league,
// normalize names (lowercase, strip accents/punct, ' and '->' & ') and map
// Odds API feed names -> logo URL. Keys are normalized team names.
//
const LOGOS: Record<string, string> = {
  "1fcunionberlin": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/598.png&h=40&w=40",
  "acmilan": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/103.png&h=40&w=40",
  "afcbournemouth": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/349.png&h=40&w=40",
  "alaves": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/96.png&h=40&w=40",
  "anaheimducks": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/ana.png&h=40&w=40",
  "arizonadiamondbacks": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/ari.png&h=40&w=40",
  "arsenal": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/359.png&h=40&w=40",
  "asroma": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/104.png&h=40&w=40",
  "astonvilla": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/362.png&h=40&w=40",
  "atalanta": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/105.png&h=40&w=40",
  "athleticclub": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/93.png&h=40&w=40",
  "athletics": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/ath.png&h=40&w=40",
  "atlantabraves": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/atl.png&h=40&w=40",
  "atlantahawks": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/atl.png&h=40&w=40",
  "atleticomadrid": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/1068.png&h=40&w=40",
  "baltimoreorioles": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/bal.png&h=40&w=40",
  "barcelona": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/83.png&h=40&w=40",
  "bayerleverkusen": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/131.png&h=40&w=40",
  "bayernmunich": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/132.png&h=40&w=40",
  "bologna": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/107.png&h=40&w=40",
  "borussiadortmund": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/124.png&h=40&w=40",
  "borussiamonchengladbach": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/268.png&h=40&w=40",
  "bostonbruins": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/bos.png&h=40&w=40",
  "bostonceltics": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/bos.png&h=40&w=40",
  "bostonredsox": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/bos.png&h=40&w=40",
  "bournemouth": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/349.png&h=40&w=40",
  "brentford": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/337.png&h=40&w=40",
  "brightonhovealbion": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/331.png&h=40&w=40",
  "brooklynnets": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/bkn.png&h=40&w=40",
  "buffalosabres": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/buf.png&h=40&w=40",
  "cagliari": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/2925.png&h=40&w=40",
  "calgaryflames": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/cgy.png&h=40&w=40",
  "carolinahurricanes": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/car.png&h=40&w=40",
  "celtavigo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/85.png&h=40&w=40",
  "charlottehornets": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/cha.png&h=40&w=40",
  "chelsea": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/363.png&h=40&w=40",
  "chicagoblackhawks": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/chi.png&h=40&w=40",
  "chicagobulls": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/chi.png&h=40&w=40",
  "chicagocubs": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/chc.png&h=40&w=40",
  "chicagowhitesox": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/chw.png&h=40&w=40",
  "cincinnatireds": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/cin.png&h=40&w=40",
  "clevelandcavaliers": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/cle.png&h=40&w=40",
  "clevelandguardians": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/cle.png&h=40&w=40",
  "coloradoavalanche": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/col.png&h=40&w=40",
  "coloradorockies": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/col.png&h=40&w=40",
  "columbusbluejackets": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/cbj.png&h=40&w=40",
  "como": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/2572.png&h=40&w=40",
  "coventrycity": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/388.png&h=40&w=40",
  "crystalpalace": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/384.png&h=40&w=40",
  "dallasmavericks": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/dal.png&h=40&w=40",
  "dallasstars": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/dal.png&h=40&w=40",
  "denvernuggets": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/den.png&h=40&w=40",
  "deportivo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/90.png&h=40&w=40",
  "detroitpistons": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/det.png&h=40&w=40",
  "detroitredwings": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/det.png&h=40&w=40",
  "detroittigers": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/det.png&h=40&w=40",
  "edmontonoilers": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/edm.png&h=40&w=40",
  "eintrachtfrankfurt": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/125.png&h=40&w=40",
  "elche": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/3751.png&h=40&w=40",
  "espanyol": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/88.png&h=40&w=40",
  "everton": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/368.png&h=40&w=40",
  "fcaugsburg": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/3841.png&h=40&w=40",
  "fccologne": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/122.png&h=40&w=40",
  "fiorentina": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/109.png&h=40&w=40",
  "floridapanthers": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/fla.png&h=40&w=40",
  "frosinone": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/4057.png&h=40&w=40",
  "fulham": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/370.png&h=40&w=40",
  "genoa": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/3263.png&h=40&w=40",
  "getafe": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/2922.png&h=40&w=40",
  "goldenstatewarriors": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/gs.png&h=40&w=40",
  "hamburgsv": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/127.png&h=40&w=40",
  "houstonastros": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/hou.png&h=40&w=40",
  "houstonrockets": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/hou.png&h=40&w=40",
  "hullcity": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/306.png&h=40&w=40",
  "indianapacers": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/ind.png&h=40&w=40",
  "internazionale": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/110.png&h=40&w=40",
  "ipswichtown": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/373.png&h=40&w=40",
  "juventus": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/111.png&h=40&w=40",
  "kansascityroyals": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/kc.png&h=40&w=40",
  "laclippers": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/lac.png&h=40&w=40",
  "lazio": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/112.png&h=40&w=40",
  "lecce": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/113.png&h=40&w=40",
  "leedsunited": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/357.png&h=40&w=40",
  "levante": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/1538.png&h=40&w=40",
  "liverpool": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/364.png&h=40&w=40",
  "losangelesangels": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/laa.png&h=40&w=40",
  "losangelesdodgers": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/lad.png&h=40&w=40",
  "losangeleskings": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/la.png&h=40&w=40",
  "losangeleslakers": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/lal.png&h=40&w=40",
  "mainz": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/2950.png&h=40&w=40",
  "malaga": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/99.png&h=40&w=40",
  "manchestercity": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/382.png&h=40&w=40",
  "manchesterunited": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/360.png&h=40&w=40",
  "memphisgrizzlies": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/mem.png&h=40&w=40",
  "miamiheat": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/mia.png&h=40&w=40",
  "miamimarlins": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/mia.png&h=40&w=40",
  "milwaukeebrewers": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/mil.png&h=40&w=40",
  "milwaukeebucks": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/mil.png&h=40&w=40",
  "minnesotatimberwolves": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/min.png&h=40&w=40",
  "minnesotatwins": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/min.png&h=40&w=40",
  "minnesotawild": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/min.png&h=40&w=40",
  "montrealcanadiens": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/mtl.png&h=40&w=40",
  "monza": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/4007.png&h=40&w=40",
  "napoli": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/114.png&h=40&w=40",
  "nashvillepredators": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/nsh.png&h=40&w=40",
  "newcastleunited": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/361.png&h=40&w=40",
  "newjerseydevils": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/nj.png&h=40&w=40",
  "neworleanspelicans": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/no.png&h=40&w=40",
  "newyorkislanders": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/nyi.png&h=40&w=40",
  "newyorkknicks": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/ny.png&h=40&w=40",
  "newyorkmets": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/nym.png&h=40&w=40",
  "newyorkrangers": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/nyr.png&h=40&w=40",
  "newyorkyankees": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/nyy.png&h=40&w=40",
  "nottinghamforest": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/393.png&h=40&w=40",
  "oklahomacitythunder": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/okc.png&h=40&w=40",
  "orlandomagic": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/orl.png&h=40&w=40",
  "osasuna": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/97.png&h=40&w=40",
  "ottawasenators": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/ott.png&h=40&w=40",
  "parma": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/115.png&h=40&w=40",
  "philadelphia76ers": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/phi.png&h=40&w=40",
  "philadelphiaflyers": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/phi.png&h=40&w=40",
  "philadelphiaphillies": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/phi.png&h=40&w=40",
  "phoenixsuns": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/phx.png&h=40&w=40",
  "pittsburghpenguins": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/pit.png&h=40&w=40",
  "pittsburghpirates": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/pit.png&h=40&w=40",
  "portlandtrailblazers": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/por.png&h=40&w=40",
  "racingsantander": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/87.png&h=40&w=40",
  "rayovallecano": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/101.png&h=40&w=40",
  "rbleipzig": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/11420.png&h=40&w=40",
  "realbetis": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/244.png&h=40&w=40",
  "realmadrid": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/86.png&h=40&w=40",
  "realsociedad": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/89.png&h=40&w=40",
  "sacramentokings": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/sac.png&h=40&w=40",
  "sanantoniospurs": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/sa.png&h=40&w=40",
  "sandiegopadres": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/sd.png&h=40&w=40",
  "sanfranciscogiants": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/sf.png&h=40&w=40",
  "sanjosesharks": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/sj.png&h=40&w=40",
  "sassuolo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/3997.png&h=40&w=40",
  "scfreiburg": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/126.png&h=40&w=40",
  "schalke04": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/133.png&h=40&w=40",
  "scpaderborn07": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/3307.png&h=40&w=40",
  "seattlekraken": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/sea.png&h=40&w=40",
  "seattlemariners": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/sea.png&h=40&w=40",
  "sevilla": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/243.png&h=40&w=40",
  "stlouisblues": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/stl.png&h=40&w=40",
  "stlouiscardinals": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/stl.png&h=40&w=40",
  "sunderland": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/366.png&h=40&w=40",
  "svelversberg": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/10388.png&h=40&w=40",
  "tampabaylightning": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/tb.png&h=40&w=40",
  "tampabayrays": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/tb.png&h=40&w=40",
  "texasrangers": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/tex.png&h=40&w=40",
  "torino": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/239.png&h=40&w=40",
  "torontobluejays": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/tor.png&h=40&w=40",
  "torontomapleleafs": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/tor.png&h=40&w=40",
  "torontoraptors": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/tor.png&h=40&w=40",
  "tottenhamhotspur": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/367.png&h=40&w=40",
  "tsghoffenheim": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/7911.png&h=40&w=40",
  "udinese": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/118.png&h=40&w=40",
  "utahjazz": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/utah.png&h=40&w=40",
  "utahmammoth": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/utah.png&h=40&w=40",
  "valencia": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/94.png&h=40&w=40",
  "vancouvercanucks": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/van.png&h=40&w=40",
  "vegasgoldenknights": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/vgk.png&h=40&w=40",
  "venezia": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/17530.png&h=40&w=40",
  "vfbstuttgart": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/134.png&h=40&w=40",
  "villarreal": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/102.png&h=40&w=40",
  "washingtoncapitals": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/wsh.png&h=40&w=40",
  "washingtonnationals": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/wsh.png&h=40&w=40",
  "washingtonwizards": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/wsh.png&h=40&w=40",
  "werderbremen": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/137.png&h=40&w=40",
  "winnipegjets": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/wpg.png&h=40&w=40",
};

const ALIASES: Record<string, string> = {
  bournemouth: "afcbournemouth", // Odds API omits "AFC"; ESPN includes it
  lalakers: "losangeleslakers", // colloquial name used in seed/UI
  mcfc: "manchestercity",
  utd: "manchesterunited",
};

/** Normalize a team name for dictionary lookup (mirrors the generator's norm()). */
export function teamLogo(name: string): string | null {
  const n = name
    .toLowerCase()
    .replace(/ and /g, " & ")
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]/g, "");
  const key = ALIASES[n] ?? n;
  return LOGOS[key] ?? null;
}

